-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce_4 is
port (
    ap_ready : OUT STD_LOGIC;
    x_0_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    x_1_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of reduce_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal zext_ln209_fu_26_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln209_1_fu_30_p1 : STD_LOGIC_VECTOR (1 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(zext_ln209_fu_26_p1) + unsigned(zext_ln209_1_fu_30_p1));
    zext_ln209_1_fu_30_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_0_V_read),2));
    zext_ln209_fu_26_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_1_V_read),2));
end behav;
