-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce_17 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x_0_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_1_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_2_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_3_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_4_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_5_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_6_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_7_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_8_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_9_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_10_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_11_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_12_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_13_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_14_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_15_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_16_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_17_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_18_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_19_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_20_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_21_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_22_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_23_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_24_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_25_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_26_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_27_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_28_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_29_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_30_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    x_31_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (21 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of reduce_17 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal grp_reduce_19_fu_268_ap_return : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_reduce_19_fu_268_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call33 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call33 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp35 : BOOLEAN;
    signal grp_reduce_19_fu_304_ap_return : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_reduce_19_fu_304_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call34 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call34 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp36 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;

    component reduce_19 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x_0_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_1_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_2_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_3_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_4_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_5_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_6_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_7_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_8_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_9_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_10_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_11_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_12_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_13_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_14_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        x_15_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_reduce_19_fu_268 : component reduce_19
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_V_read => x_0_V_read,
        x_1_V_read => x_1_V_read,
        x_2_V_read => x_2_V_read,
        x_3_V_read => x_3_V_read,
        x_4_V_read => x_4_V_read,
        x_5_V_read => x_5_V_read,
        x_6_V_read => x_6_V_read,
        x_7_V_read => x_7_V_read,
        x_8_V_read => x_8_V_read,
        x_9_V_read => x_9_V_read,
        x_10_V_read => x_10_V_read,
        x_11_V_read => x_11_V_read,
        x_12_V_read => x_12_V_read,
        x_13_V_read => x_13_V_read,
        x_14_V_read => x_14_V_read,
        x_15_V_read => x_15_V_read,
        ap_return => grp_reduce_19_fu_268_ap_return,
        ap_ce => grp_reduce_19_fu_268_ap_ce);

    grp_reduce_19_fu_304 : component reduce_19
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_V_read => x_16_V_read,
        x_1_V_read => x_17_V_read,
        x_2_V_read => x_18_V_read,
        x_3_V_read => x_19_V_read,
        x_4_V_read => x_20_V_read,
        x_5_V_read => x_21_V_read,
        x_6_V_read => x_22_V_read,
        x_7_V_read => x_23_V_read,
        x_8_V_read => x_24_V_read,
        x_9_V_read => x_25_V_read,
        x_10_V_read => x_26_V_read,
        x_11_V_read => x_27_V_read,
        x_12_V_read => x_28_V_read,
        x_13_V_read => x_29_V_read,
        x_14_V_read => x_30_V_read,
        x_15_V_read => x_31_V_read,
        ap_return => grp_reduce_19_fu_304_ap_return,
        ap_ce => grp_reduce_19_fu_304_ap_ce);




        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp35 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= std_logic_vector(unsigned(grp_reduce_19_fu_304_ap_return) + unsigned(grp_reduce_19_fu_268_ap_return));

    grp_reduce_19_fu_268_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp35, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp35) and (ap_const_logic_1 = ap_ce))) then 
            grp_reduce_19_fu_268_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_19_fu_268_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reduce_19_fu_304_ap_ce_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp36)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp36) and (ap_const_logic_1 = ap_ce))) then 
            grp_reduce_19_fu_304_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_19_fu_304_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

end behav;
