-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of reduce is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal grp_reduce_2_fu_210_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_2_fu_210_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_2_fu_210_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_2_fu_210_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call25 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call25 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp27 : BOOLEAN;
    signal grp_reduce_2_fu_238_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_2_fu_238_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_2_fu_238_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_2_fu_238_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call29 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call29 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp28 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln1496_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1496_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_fu_302_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln84_1_fu_310_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln84_2_fu_318_p3 : STD_LOGIC_VECTOR (9 downto 0);

    component reduce_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_reduce_2_fu_210 : component reduce_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_hwPt_V_read => x_0_hwPt_V_read,
        x_1_hwPt_V_read => x_1_hwPt_V_read,
        x_2_hwPt_V_read => x_2_hwPt_V_read,
        x_3_hwPt_V_read => x_3_hwPt_V_read,
        x_0_hwEta_V_read => x_0_hwEta_V_read,
        x_1_hwEta_V_read => x_1_hwEta_V_read,
        x_2_hwEta_V_read => x_2_hwEta_V_read,
        x_3_hwEta_V_read => x_3_hwEta_V_read,
        x_0_hwPhi_V_read => x_0_hwPhi_V_read,
        x_1_hwPhi_V_read => x_1_hwPhi_V_read,
        x_2_hwPhi_V_read => x_2_hwPhi_V_read,
        x_3_hwPhi_V_read => x_3_hwPhi_V_read,
        ap_return_0 => grp_reduce_2_fu_210_ap_return_0,
        ap_return_1 => grp_reduce_2_fu_210_ap_return_1,
        ap_return_2 => grp_reduce_2_fu_210_ap_return_2,
        ap_ce => grp_reduce_2_fu_210_ap_ce);

    grp_reduce_2_fu_238 : component reduce_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_hwPt_V_read => x_4_hwPt_V_read,
        x_1_hwPt_V_read => x_5_hwPt_V_read,
        x_2_hwPt_V_read => x_6_hwPt_V_read,
        x_3_hwPt_V_read => x_7_hwPt_V_read,
        x_0_hwEta_V_read => x_4_hwEta_V_read,
        x_1_hwEta_V_read => x_5_hwEta_V_read,
        x_2_hwEta_V_read => x_6_hwEta_V_read,
        x_3_hwEta_V_read => x_7_hwEta_V_read,
        x_0_hwPhi_V_read => x_4_hwPhi_V_read,
        x_1_hwPhi_V_read => x_5_hwPhi_V_read,
        x_2_hwPhi_V_read => x_6_hwPhi_V_read,
        x_3_hwPhi_V_read => x_7_hwPhi_V_read,
        ap_return_0 => grp_reduce_2_fu_238_ap_return_0,
        ap_return_1 => grp_reduce_2_fu_238_ap_return_1,
        ap_return_2 => grp_reduce_2_fu_238_ap_return_2,
        ap_ce => grp_reduce_2_fu_238_ap_ce);




        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call29 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call29 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= select_ln84_fu_302_p3;
    ap_return_1 <= select_ln84_1_fu_310_p3;
    ap_return_2 <= select_ln84_2_fu_318_p3;

    grp_reduce_2_fu_210_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp27, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp27) and (ap_const_logic_1 = ap_ce))) then 
            grp_reduce_2_fu_210_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_2_fu_210_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reduce_2_fu_238_ap_ce_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp28)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp28) and (ap_const_logic_1 = ap_ce))) then 
            grp_reduce_2_fu_238_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_2_fu_238_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1496_fu_290_p2 <= "1" when (unsigned(grp_reduce_2_fu_210_ap_return_0) < unsigned(grp_reduce_2_fu_238_ap_return_0)) else "0";
    select_ln84_1_fu_310_p3 <= 
        grp_reduce_2_fu_210_ap_return_1 when (xor_ln1496_fu_296_p2(0) = '1') else 
        grp_reduce_2_fu_238_ap_return_1;
    select_ln84_2_fu_318_p3 <= 
        grp_reduce_2_fu_210_ap_return_2 when (xor_ln1496_fu_296_p2(0) = '1') else 
        grp_reduce_2_fu_238_ap_return_2;
    select_ln84_fu_302_p3 <= 
        grp_reduce_2_fu_210_ap_return_0 when (xor_ln1496_fu_296_p2(0) = '1') else 
        grp_reduce_2_fu_238_ap_return_0;
    xor_ln1496_fu_296_p2 <= (icmp_ln1496_fu_290_p2 xor ap_const_lv1_1);
end behav;
