-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_10_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_11_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_12_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_13_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_14_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_15_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_16_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_17_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_18_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_19_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_20_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_21_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_22_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_23_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_24_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_25_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_26_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_27_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_28_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_29_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_30_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_31_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_10_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_11_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_12_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_13_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_14_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_15_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_16_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_17_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_18_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_19_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_20_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_21_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_22_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_23_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_24_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_25_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_26_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_27_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_28_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_29_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_30_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_31_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_10_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_11_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_12_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_13_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_14_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_15_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_16_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_17_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_18_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_19_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_20_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_21_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_22_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_23_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_24_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_25_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_26_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_27_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_28_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_29_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_30_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_31_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of reduce_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_reduce_5_fu_786_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_5_fu_786_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_5_fu_786_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal call_ret7_reg_1537_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal call_ret7_reg_1537_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_5_fu_886_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_5_fu_886_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_5_fu_886_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal call_ret8_reg_1543_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal call_ret8_reg_1543_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln1496_fu_1000_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1496_reg_1549 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_fu_1006_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln84_reg_1555 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_5_fu_786_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call97 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call97 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call97 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call97 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call97 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp102 : BOOLEAN;
    signal grp_reduce_5_fu_886_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call101 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call101 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call101 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call101 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call101 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp103 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln1496_fu_994_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_7_fu_1026_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln84_8_fu_1033_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_0_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_2_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_3_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_4_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_5_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_6_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_7_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_8_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_9_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_10_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_11_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_12_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_13_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_14_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_15_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_16_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_17_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_18_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_19_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_20_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_21_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_22_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_23_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_24_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_25_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_26_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_27_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_28_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_29_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_30_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_31_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_0_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_2_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_3_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_4_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_5_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_6_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_7_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_8_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_9_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_10_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_11_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_12_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_13_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_14_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_15_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_16_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_17_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_18_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_19_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_20_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_21_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_22_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_23_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_24_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_25_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_26_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_27_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_28_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_29_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_30_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_31_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_0_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_2_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_3_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_4_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_5_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_6_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_7_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_8_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_9_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_10_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_11_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_12_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_13_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_14_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_15_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_16_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_17_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_18_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_19_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_20_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_21_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_22_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_23_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_24_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_25_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_26_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_27_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_28_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_29_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_30_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_31_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);

    component reduce_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_10_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_11_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_12_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_13_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_14_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_15_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_10_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_11_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_12_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_13_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_14_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_15_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_10_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_11_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_12_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_13_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_14_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_15_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_reduce_5_fu_786 : component reduce_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_hwPt_V_read => x_0_hwPt_V_read_int_reg,
        x_1_hwPt_V_read => x_1_hwPt_V_read_int_reg,
        x_2_hwPt_V_read => x_2_hwPt_V_read_int_reg,
        x_3_hwPt_V_read => x_3_hwPt_V_read_int_reg,
        x_4_hwPt_V_read => x_4_hwPt_V_read_int_reg,
        x_5_hwPt_V_read => x_5_hwPt_V_read_int_reg,
        x_6_hwPt_V_read => x_6_hwPt_V_read_int_reg,
        x_7_hwPt_V_read => x_7_hwPt_V_read_int_reg,
        x_8_hwPt_V_read => x_8_hwPt_V_read_int_reg,
        x_9_hwPt_V_read => x_9_hwPt_V_read_int_reg,
        x_10_hwPt_V_read => x_10_hwPt_V_read_int_reg,
        x_11_hwPt_V_read => x_11_hwPt_V_read_int_reg,
        x_12_hwPt_V_read => x_12_hwPt_V_read_int_reg,
        x_13_hwPt_V_read => x_13_hwPt_V_read_int_reg,
        x_14_hwPt_V_read => x_14_hwPt_V_read_int_reg,
        x_15_hwPt_V_read => x_15_hwPt_V_read_int_reg,
        x_0_hwEta_V_read => x_0_hwEta_V_read_int_reg,
        x_1_hwEta_V_read => x_1_hwEta_V_read_int_reg,
        x_2_hwEta_V_read => x_2_hwEta_V_read_int_reg,
        x_3_hwEta_V_read => x_3_hwEta_V_read_int_reg,
        x_4_hwEta_V_read => x_4_hwEta_V_read_int_reg,
        x_5_hwEta_V_read => x_5_hwEta_V_read_int_reg,
        x_6_hwEta_V_read => x_6_hwEta_V_read_int_reg,
        x_7_hwEta_V_read => x_7_hwEta_V_read_int_reg,
        x_8_hwEta_V_read => x_8_hwEta_V_read_int_reg,
        x_9_hwEta_V_read => x_9_hwEta_V_read_int_reg,
        x_10_hwEta_V_read => x_10_hwEta_V_read_int_reg,
        x_11_hwEta_V_read => x_11_hwEta_V_read_int_reg,
        x_12_hwEta_V_read => x_12_hwEta_V_read_int_reg,
        x_13_hwEta_V_read => x_13_hwEta_V_read_int_reg,
        x_14_hwEta_V_read => x_14_hwEta_V_read_int_reg,
        x_15_hwEta_V_read => x_15_hwEta_V_read_int_reg,
        x_0_hwPhi_V_read => x_0_hwPhi_V_read_int_reg,
        x_1_hwPhi_V_read => x_1_hwPhi_V_read_int_reg,
        x_2_hwPhi_V_read => x_2_hwPhi_V_read_int_reg,
        x_3_hwPhi_V_read => x_3_hwPhi_V_read_int_reg,
        x_4_hwPhi_V_read => x_4_hwPhi_V_read_int_reg,
        x_5_hwPhi_V_read => x_5_hwPhi_V_read_int_reg,
        x_6_hwPhi_V_read => x_6_hwPhi_V_read_int_reg,
        x_7_hwPhi_V_read => x_7_hwPhi_V_read_int_reg,
        x_8_hwPhi_V_read => x_8_hwPhi_V_read_int_reg,
        x_9_hwPhi_V_read => x_9_hwPhi_V_read_int_reg,
        x_10_hwPhi_V_read => x_10_hwPhi_V_read_int_reg,
        x_11_hwPhi_V_read => x_11_hwPhi_V_read_int_reg,
        x_12_hwPhi_V_read => x_12_hwPhi_V_read_int_reg,
        x_13_hwPhi_V_read => x_13_hwPhi_V_read_int_reg,
        x_14_hwPhi_V_read => x_14_hwPhi_V_read_int_reg,
        x_15_hwPhi_V_read => x_15_hwPhi_V_read_int_reg,
        ap_return_0 => grp_reduce_5_fu_786_ap_return_0,
        ap_return_1 => grp_reduce_5_fu_786_ap_return_1,
        ap_return_2 => grp_reduce_5_fu_786_ap_return_2,
        ap_ce => grp_reduce_5_fu_786_ap_ce);

    grp_reduce_5_fu_886 : component reduce_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_hwPt_V_read => x_16_hwPt_V_read_int_reg,
        x_1_hwPt_V_read => x_17_hwPt_V_read_int_reg,
        x_2_hwPt_V_read => x_18_hwPt_V_read_int_reg,
        x_3_hwPt_V_read => x_19_hwPt_V_read_int_reg,
        x_4_hwPt_V_read => x_20_hwPt_V_read_int_reg,
        x_5_hwPt_V_read => x_21_hwPt_V_read_int_reg,
        x_6_hwPt_V_read => x_22_hwPt_V_read_int_reg,
        x_7_hwPt_V_read => x_23_hwPt_V_read_int_reg,
        x_8_hwPt_V_read => x_24_hwPt_V_read_int_reg,
        x_9_hwPt_V_read => x_25_hwPt_V_read_int_reg,
        x_10_hwPt_V_read => x_26_hwPt_V_read_int_reg,
        x_11_hwPt_V_read => x_27_hwPt_V_read_int_reg,
        x_12_hwPt_V_read => x_28_hwPt_V_read_int_reg,
        x_13_hwPt_V_read => x_29_hwPt_V_read_int_reg,
        x_14_hwPt_V_read => x_30_hwPt_V_read_int_reg,
        x_15_hwPt_V_read => x_31_hwPt_V_read_int_reg,
        x_0_hwEta_V_read => x_16_hwEta_V_read_int_reg,
        x_1_hwEta_V_read => x_17_hwEta_V_read_int_reg,
        x_2_hwEta_V_read => x_18_hwEta_V_read_int_reg,
        x_3_hwEta_V_read => x_19_hwEta_V_read_int_reg,
        x_4_hwEta_V_read => x_20_hwEta_V_read_int_reg,
        x_5_hwEta_V_read => x_21_hwEta_V_read_int_reg,
        x_6_hwEta_V_read => x_22_hwEta_V_read_int_reg,
        x_7_hwEta_V_read => x_23_hwEta_V_read_int_reg,
        x_8_hwEta_V_read => x_24_hwEta_V_read_int_reg,
        x_9_hwEta_V_read => x_25_hwEta_V_read_int_reg,
        x_10_hwEta_V_read => x_26_hwEta_V_read_int_reg,
        x_11_hwEta_V_read => x_27_hwEta_V_read_int_reg,
        x_12_hwEta_V_read => x_28_hwEta_V_read_int_reg,
        x_13_hwEta_V_read => x_29_hwEta_V_read_int_reg,
        x_14_hwEta_V_read => x_30_hwEta_V_read_int_reg,
        x_15_hwEta_V_read => x_31_hwEta_V_read_int_reg,
        x_0_hwPhi_V_read => x_16_hwPhi_V_read_int_reg,
        x_1_hwPhi_V_read => x_17_hwPhi_V_read_int_reg,
        x_2_hwPhi_V_read => x_18_hwPhi_V_read_int_reg,
        x_3_hwPhi_V_read => x_19_hwPhi_V_read_int_reg,
        x_4_hwPhi_V_read => x_20_hwPhi_V_read_int_reg,
        x_5_hwPhi_V_read => x_21_hwPhi_V_read_int_reg,
        x_6_hwPhi_V_read => x_22_hwPhi_V_read_int_reg,
        x_7_hwPhi_V_read => x_23_hwPhi_V_read_int_reg,
        x_8_hwPhi_V_read => x_24_hwPhi_V_read_int_reg,
        x_9_hwPhi_V_read => x_25_hwPhi_V_read_int_reg,
        x_10_hwPhi_V_read => x_26_hwPhi_V_read_int_reg,
        x_11_hwPhi_V_read => x_27_hwPhi_V_read_int_reg,
        x_12_hwPhi_V_read => x_28_hwPhi_V_read_int_reg,
        x_13_hwPhi_V_read => x_29_hwPhi_V_read_int_reg,
        x_14_hwPhi_V_read => x_30_hwPhi_V_read_int_reg,
        x_15_hwPhi_V_read => x_31_hwPhi_V_read_int_reg,
        ap_return_0 => grp_reduce_5_fu_886_ap_return_0,
        ap_return_1 => grp_reduce_5_fu_886_ap_return_1,
        ap_return_2 => grp_reduce_5_fu_886_ap_return_2,
        ap_ce => grp_reduce_5_fu_886_ap_ce);




    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                call_ret7_reg_1537_1 <= grp_reduce_5_fu_786_ap_return_1;
                call_ret7_reg_1537_2 <= grp_reduce_5_fu_786_ap_return_2;
                call_ret8_reg_1543_1 <= grp_reduce_5_fu_886_ap_return_1;
                call_ret8_reg_1543_2 <= grp_reduce_5_fu_886_ap_return_2;
                select_ln84_reg_1555 <= select_ln84_fu_1006_p3;
                xor_ln1496_reg_1549 <= xor_ln1496_fu_1000_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_0_hwEta_V_read_int_reg <= x_0_hwEta_V_read;
                x_0_hwPhi_V_read_int_reg <= x_0_hwPhi_V_read;
                x_0_hwPt_V_read_int_reg <= x_0_hwPt_V_read;
                x_10_hwEta_V_read_int_reg <= x_10_hwEta_V_read;
                x_10_hwPhi_V_read_int_reg <= x_10_hwPhi_V_read;
                x_10_hwPt_V_read_int_reg <= x_10_hwPt_V_read;
                x_11_hwEta_V_read_int_reg <= x_11_hwEta_V_read;
                x_11_hwPhi_V_read_int_reg <= x_11_hwPhi_V_read;
                x_11_hwPt_V_read_int_reg <= x_11_hwPt_V_read;
                x_12_hwEta_V_read_int_reg <= x_12_hwEta_V_read;
                x_12_hwPhi_V_read_int_reg <= x_12_hwPhi_V_read;
                x_12_hwPt_V_read_int_reg <= x_12_hwPt_V_read;
                x_13_hwEta_V_read_int_reg <= x_13_hwEta_V_read;
                x_13_hwPhi_V_read_int_reg <= x_13_hwPhi_V_read;
                x_13_hwPt_V_read_int_reg <= x_13_hwPt_V_read;
                x_14_hwEta_V_read_int_reg <= x_14_hwEta_V_read;
                x_14_hwPhi_V_read_int_reg <= x_14_hwPhi_V_read;
                x_14_hwPt_V_read_int_reg <= x_14_hwPt_V_read;
                x_15_hwEta_V_read_int_reg <= x_15_hwEta_V_read;
                x_15_hwPhi_V_read_int_reg <= x_15_hwPhi_V_read;
                x_15_hwPt_V_read_int_reg <= x_15_hwPt_V_read;
                x_16_hwEta_V_read_int_reg <= x_16_hwEta_V_read;
                x_16_hwPhi_V_read_int_reg <= x_16_hwPhi_V_read;
                x_16_hwPt_V_read_int_reg <= x_16_hwPt_V_read;
                x_17_hwEta_V_read_int_reg <= x_17_hwEta_V_read;
                x_17_hwPhi_V_read_int_reg <= x_17_hwPhi_V_read;
                x_17_hwPt_V_read_int_reg <= x_17_hwPt_V_read;
                x_18_hwEta_V_read_int_reg <= x_18_hwEta_V_read;
                x_18_hwPhi_V_read_int_reg <= x_18_hwPhi_V_read;
                x_18_hwPt_V_read_int_reg <= x_18_hwPt_V_read;
                x_19_hwEta_V_read_int_reg <= x_19_hwEta_V_read;
                x_19_hwPhi_V_read_int_reg <= x_19_hwPhi_V_read;
                x_19_hwPt_V_read_int_reg <= x_19_hwPt_V_read;
                x_1_hwEta_V_read_int_reg <= x_1_hwEta_V_read;
                x_1_hwPhi_V_read_int_reg <= x_1_hwPhi_V_read;
                x_1_hwPt_V_read_int_reg <= x_1_hwPt_V_read;
                x_20_hwEta_V_read_int_reg <= x_20_hwEta_V_read;
                x_20_hwPhi_V_read_int_reg <= x_20_hwPhi_V_read;
                x_20_hwPt_V_read_int_reg <= x_20_hwPt_V_read;
                x_21_hwEta_V_read_int_reg <= x_21_hwEta_V_read;
                x_21_hwPhi_V_read_int_reg <= x_21_hwPhi_V_read;
                x_21_hwPt_V_read_int_reg <= x_21_hwPt_V_read;
                x_22_hwEta_V_read_int_reg <= x_22_hwEta_V_read;
                x_22_hwPhi_V_read_int_reg <= x_22_hwPhi_V_read;
                x_22_hwPt_V_read_int_reg <= x_22_hwPt_V_read;
                x_23_hwEta_V_read_int_reg <= x_23_hwEta_V_read;
                x_23_hwPhi_V_read_int_reg <= x_23_hwPhi_V_read;
                x_23_hwPt_V_read_int_reg <= x_23_hwPt_V_read;
                x_24_hwEta_V_read_int_reg <= x_24_hwEta_V_read;
                x_24_hwPhi_V_read_int_reg <= x_24_hwPhi_V_read;
                x_24_hwPt_V_read_int_reg <= x_24_hwPt_V_read;
                x_25_hwEta_V_read_int_reg <= x_25_hwEta_V_read;
                x_25_hwPhi_V_read_int_reg <= x_25_hwPhi_V_read;
                x_25_hwPt_V_read_int_reg <= x_25_hwPt_V_read;
                x_26_hwEta_V_read_int_reg <= x_26_hwEta_V_read;
                x_26_hwPhi_V_read_int_reg <= x_26_hwPhi_V_read;
                x_26_hwPt_V_read_int_reg <= x_26_hwPt_V_read;
                x_27_hwEta_V_read_int_reg <= x_27_hwEta_V_read;
                x_27_hwPhi_V_read_int_reg <= x_27_hwPhi_V_read;
                x_27_hwPt_V_read_int_reg <= x_27_hwPt_V_read;
                x_28_hwEta_V_read_int_reg <= x_28_hwEta_V_read;
                x_28_hwPhi_V_read_int_reg <= x_28_hwPhi_V_read;
                x_28_hwPt_V_read_int_reg <= x_28_hwPt_V_read;
                x_29_hwEta_V_read_int_reg <= x_29_hwEta_V_read;
                x_29_hwPhi_V_read_int_reg <= x_29_hwPhi_V_read;
                x_29_hwPt_V_read_int_reg <= x_29_hwPt_V_read;
                x_2_hwEta_V_read_int_reg <= x_2_hwEta_V_read;
                x_2_hwPhi_V_read_int_reg <= x_2_hwPhi_V_read;
                x_2_hwPt_V_read_int_reg <= x_2_hwPt_V_read;
                x_30_hwEta_V_read_int_reg <= x_30_hwEta_V_read;
                x_30_hwPhi_V_read_int_reg <= x_30_hwPhi_V_read;
                x_30_hwPt_V_read_int_reg <= x_30_hwPt_V_read;
                x_31_hwEta_V_read_int_reg <= x_31_hwEta_V_read;
                x_31_hwPhi_V_read_int_reg <= x_31_hwPhi_V_read;
                x_31_hwPt_V_read_int_reg <= x_31_hwPt_V_read;
                x_3_hwEta_V_read_int_reg <= x_3_hwEta_V_read;
                x_3_hwPhi_V_read_int_reg <= x_3_hwPhi_V_read;
                x_3_hwPt_V_read_int_reg <= x_3_hwPt_V_read;
                x_4_hwEta_V_read_int_reg <= x_4_hwEta_V_read;
                x_4_hwPhi_V_read_int_reg <= x_4_hwPhi_V_read;
                x_4_hwPt_V_read_int_reg <= x_4_hwPt_V_read;
                x_5_hwEta_V_read_int_reg <= x_5_hwEta_V_read;
                x_5_hwPhi_V_read_int_reg <= x_5_hwPhi_V_read;
                x_5_hwPt_V_read_int_reg <= x_5_hwPt_V_read;
                x_6_hwEta_V_read_int_reg <= x_6_hwEta_V_read;
                x_6_hwPhi_V_read_int_reg <= x_6_hwPhi_V_read;
                x_6_hwPt_V_read_int_reg <= x_6_hwPt_V_read;
                x_7_hwEta_V_read_int_reg <= x_7_hwEta_V_read;
                x_7_hwPhi_V_read_int_reg <= x_7_hwPhi_V_read;
                x_7_hwPt_V_read_int_reg <= x_7_hwPt_V_read;
                x_8_hwEta_V_read_int_reg <= x_8_hwEta_V_read;
                x_8_hwPhi_V_read_int_reg <= x_8_hwPhi_V_read;
                x_8_hwPt_V_read_int_reg <= x_8_hwPt_V_read;
                x_9_hwEta_V_read_int_reg <= x_9_hwEta_V_read;
                x_9_hwPhi_V_read_int_reg <= x_9_hwPhi_V_read;
                x_9_hwPt_V_read_int_reg <= x_9_hwPt_V_read;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp102 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp103 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call101 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call97 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call101 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call97 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call101 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call97 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call101 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call97 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call101 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call97 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= select_ln84_reg_1555;
    ap_return_1 <= select_ln84_7_fu_1026_p3;
    ap_return_2 <= select_ln84_8_fu_1033_p3;

    grp_reduce_5_fu_786_ap_ce_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp102)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp102) and (ap_const_logic_1 = ap_ce))) then 
            grp_reduce_5_fu_786_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_5_fu_786_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reduce_5_fu_886_ap_ce_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp103)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp103) and (ap_const_logic_1 = ap_ce))) then 
            grp_reduce_5_fu_886_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_5_fu_886_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1496_fu_994_p2 <= "1" when (unsigned(grp_reduce_5_fu_786_ap_return_0) < unsigned(grp_reduce_5_fu_886_ap_return_0)) else "0";
    select_ln84_7_fu_1026_p3 <= 
        call_ret7_reg_1537_1 when (xor_ln1496_reg_1549(0) = '1') else 
        call_ret8_reg_1543_1;
    select_ln84_8_fu_1033_p3 <= 
        call_ret7_reg_1537_2 when (xor_ln1496_reg_1549(0) = '1') else 
        call_ret8_reg_1543_2;
    select_ln84_fu_1006_p3 <= 
        grp_reduce_5_fu_786_ap_return_0 when (xor_ln1496_fu_1000_p2(0) = '1') else 
        grp_reduce_5_fu_886_ap_return_0;
    xor_ln1496_fu_1000_p2 <= (icmp_ln1496_fu_994_p2 xor ap_const_lv1_1);
end behav;
