-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_10_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_11_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_12_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_13_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_14_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_15_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_16_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_17_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_18_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_19_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_20_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_21_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_22_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_23_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_24_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_25_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_26_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_27_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_28_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_29_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_30_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_31_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_32_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_33_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_34_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_35_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_36_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_37_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_38_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_39_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_40_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_41_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_42_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_43_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_44_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_45_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_46_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_47_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_48_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_49_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_50_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_51_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_52_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_53_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_54_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_55_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_56_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_57_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_58_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_59_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_60_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_61_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_62_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_63_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_10_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_11_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_12_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_13_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_14_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_15_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_16_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_17_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_18_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_19_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_20_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_21_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_22_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_23_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_24_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_25_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_26_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_27_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_28_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_29_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_30_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_31_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_32_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_33_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_34_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_35_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_36_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_37_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_38_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_39_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_40_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_41_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_42_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_43_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_44_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_45_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_46_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_47_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_48_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_49_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_50_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_51_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_52_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_53_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_54_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_55_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_56_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_57_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_58_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_59_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_60_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_61_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_62_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_63_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_10_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_11_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_12_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_13_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_14_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_15_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_16_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_17_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_18_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_19_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_20_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_21_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_22_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_23_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_24_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_25_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_26_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_27_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_28_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_29_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_30_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_31_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_32_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_33_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_34_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_35_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_36_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_37_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_38_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_39_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_40_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_41_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_42_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_43_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_44_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_45_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_46_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_47_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_48_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_49_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_50_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_51_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_52_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_53_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_54_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_55_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_56_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_57_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_58_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_59_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_60_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_61_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_62_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_63_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of reduce_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_reduce_3_fu_1554_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_3_fu_1554_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_3_fu_1554_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_3_fu_1554_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call193 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call193 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call193 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call193 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call193 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call193 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp199 : BOOLEAN;
    signal grp_reduce_3_fu_1750_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_3_fu_1750_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_3_fu_1750_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_3_fu_1750_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call197 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call197 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call197 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call197 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call197 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call197 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp200 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln1496_fu_1970_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1496_fu_1976_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_fu_1982_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln84_3_fu_1990_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln84_4_fu_1998_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_0_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_2_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_3_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_4_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_5_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_6_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_7_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_8_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_9_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_10_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_11_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_12_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_13_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_14_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_15_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_16_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_17_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_18_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_19_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_20_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_21_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_22_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_23_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_24_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_25_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_26_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_27_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_28_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_29_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_30_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_31_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_32_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_33_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_34_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_35_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_36_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_37_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_38_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_39_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_40_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_41_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_42_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_43_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_44_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_45_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_46_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_47_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_48_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_49_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_50_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_51_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_52_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_53_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_54_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_55_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_56_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_57_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_58_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_59_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_60_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_61_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_62_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_63_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_0_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_2_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_3_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_4_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_5_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_6_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_7_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_8_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_9_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_10_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_11_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_12_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_13_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_14_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_15_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_16_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_17_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_18_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_19_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_20_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_21_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_22_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_23_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_24_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_25_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_26_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_27_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_28_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_29_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_30_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_31_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_32_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_33_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_34_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_35_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_36_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_37_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_38_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_39_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_40_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_41_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_42_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_43_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_44_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_45_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_46_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_47_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_48_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_49_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_50_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_51_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_52_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_53_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_54_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_55_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_56_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_57_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_58_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_59_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_60_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_61_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_62_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_63_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_0_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_2_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_3_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_4_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_5_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_6_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_7_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_8_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_9_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_10_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_11_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_12_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_13_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_14_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_15_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_16_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_17_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_18_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_19_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_20_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_21_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_22_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_23_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_24_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_25_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_26_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_27_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_28_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_29_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_30_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_31_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_32_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_33_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_34_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_35_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_36_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_37_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_38_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_39_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_40_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_41_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_42_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_43_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_44_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_45_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_46_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_47_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_48_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_49_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_50_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_51_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_52_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_53_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_54_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_55_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_56_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_57_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_58_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_59_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_60_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_61_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_62_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_63_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (9 downto 0);

    component reduce_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_10_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_11_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_12_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_13_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_14_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_15_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_16_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_17_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_18_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_19_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_20_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_21_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_22_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_23_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_24_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_25_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_26_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_27_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_28_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_29_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_30_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_31_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_10_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_11_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_12_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_13_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_14_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_15_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_16_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_17_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_18_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_19_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_20_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_21_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_22_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_23_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_24_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_25_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_26_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_27_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_28_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_29_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_30_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_31_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_10_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_11_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_12_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_13_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_14_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_15_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_16_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_17_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_18_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_19_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_20_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_21_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_22_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_23_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_24_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_25_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_26_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_27_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_28_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_29_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_30_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_31_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_reduce_3_fu_1554 : component reduce_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_hwPt_V_read => x_0_hwPt_V_read_int_reg,
        x_1_hwPt_V_read => x_1_hwPt_V_read_int_reg,
        x_2_hwPt_V_read => x_2_hwPt_V_read_int_reg,
        x_3_hwPt_V_read => x_3_hwPt_V_read_int_reg,
        x_4_hwPt_V_read => x_4_hwPt_V_read_int_reg,
        x_5_hwPt_V_read => x_5_hwPt_V_read_int_reg,
        x_6_hwPt_V_read => x_6_hwPt_V_read_int_reg,
        x_7_hwPt_V_read => x_7_hwPt_V_read_int_reg,
        x_8_hwPt_V_read => x_8_hwPt_V_read_int_reg,
        x_9_hwPt_V_read => x_9_hwPt_V_read_int_reg,
        x_10_hwPt_V_read => x_10_hwPt_V_read_int_reg,
        x_11_hwPt_V_read => x_11_hwPt_V_read_int_reg,
        x_12_hwPt_V_read => x_12_hwPt_V_read_int_reg,
        x_13_hwPt_V_read => x_13_hwPt_V_read_int_reg,
        x_14_hwPt_V_read => x_14_hwPt_V_read_int_reg,
        x_15_hwPt_V_read => x_15_hwPt_V_read_int_reg,
        x_16_hwPt_V_read => x_16_hwPt_V_read_int_reg,
        x_17_hwPt_V_read => x_17_hwPt_V_read_int_reg,
        x_18_hwPt_V_read => x_18_hwPt_V_read_int_reg,
        x_19_hwPt_V_read => x_19_hwPt_V_read_int_reg,
        x_20_hwPt_V_read => x_20_hwPt_V_read_int_reg,
        x_21_hwPt_V_read => x_21_hwPt_V_read_int_reg,
        x_22_hwPt_V_read => x_22_hwPt_V_read_int_reg,
        x_23_hwPt_V_read => x_23_hwPt_V_read_int_reg,
        x_24_hwPt_V_read => x_24_hwPt_V_read_int_reg,
        x_25_hwPt_V_read => x_25_hwPt_V_read_int_reg,
        x_26_hwPt_V_read => x_26_hwPt_V_read_int_reg,
        x_27_hwPt_V_read => x_27_hwPt_V_read_int_reg,
        x_28_hwPt_V_read => x_28_hwPt_V_read_int_reg,
        x_29_hwPt_V_read => x_29_hwPt_V_read_int_reg,
        x_30_hwPt_V_read => x_30_hwPt_V_read_int_reg,
        x_31_hwPt_V_read => x_31_hwPt_V_read_int_reg,
        x_0_hwEta_V_read => x_0_hwEta_V_read_int_reg,
        x_1_hwEta_V_read => x_1_hwEta_V_read_int_reg,
        x_2_hwEta_V_read => x_2_hwEta_V_read_int_reg,
        x_3_hwEta_V_read => x_3_hwEta_V_read_int_reg,
        x_4_hwEta_V_read => x_4_hwEta_V_read_int_reg,
        x_5_hwEta_V_read => x_5_hwEta_V_read_int_reg,
        x_6_hwEta_V_read => x_6_hwEta_V_read_int_reg,
        x_7_hwEta_V_read => x_7_hwEta_V_read_int_reg,
        x_8_hwEta_V_read => x_8_hwEta_V_read_int_reg,
        x_9_hwEta_V_read => x_9_hwEta_V_read_int_reg,
        x_10_hwEta_V_read => x_10_hwEta_V_read_int_reg,
        x_11_hwEta_V_read => x_11_hwEta_V_read_int_reg,
        x_12_hwEta_V_read => x_12_hwEta_V_read_int_reg,
        x_13_hwEta_V_read => x_13_hwEta_V_read_int_reg,
        x_14_hwEta_V_read => x_14_hwEta_V_read_int_reg,
        x_15_hwEta_V_read => x_15_hwEta_V_read_int_reg,
        x_16_hwEta_V_read => x_16_hwEta_V_read_int_reg,
        x_17_hwEta_V_read => x_17_hwEta_V_read_int_reg,
        x_18_hwEta_V_read => x_18_hwEta_V_read_int_reg,
        x_19_hwEta_V_read => x_19_hwEta_V_read_int_reg,
        x_20_hwEta_V_read => x_20_hwEta_V_read_int_reg,
        x_21_hwEta_V_read => x_21_hwEta_V_read_int_reg,
        x_22_hwEta_V_read => x_22_hwEta_V_read_int_reg,
        x_23_hwEta_V_read => x_23_hwEta_V_read_int_reg,
        x_24_hwEta_V_read => x_24_hwEta_V_read_int_reg,
        x_25_hwEta_V_read => x_25_hwEta_V_read_int_reg,
        x_26_hwEta_V_read => x_26_hwEta_V_read_int_reg,
        x_27_hwEta_V_read => x_27_hwEta_V_read_int_reg,
        x_28_hwEta_V_read => x_28_hwEta_V_read_int_reg,
        x_29_hwEta_V_read => x_29_hwEta_V_read_int_reg,
        x_30_hwEta_V_read => x_30_hwEta_V_read_int_reg,
        x_31_hwEta_V_read => x_31_hwEta_V_read_int_reg,
        x_0_hwPhi_V_read => x_0_hwPhi_V_read_int_reg,
        x_1_hwPhi_V_read => x_1_hwPhi_V_read_int_reg,
        x_2_hwPhi_V_read => x_2_hwPhi_V_read_int_reg,
        x_3_hwPhi_V_read => x_3_hwPhi_V_read_int_reg,
        x_4_hwPhi_V_read => x_4_hwPhi_V_read_int_reg,
        x_5_hwPhi_V_read => x_5_hwPhi_V_read_int_reg,
        x_6_hwPhi_V_read => x_6_hwPhi_V_read_int_reg,
        x_7_hwPhi_V_read => x_7_hwPhi_V_read_int_reg,
        x_8_hwPhi_V_read => x_8_hwPhi_V_read_int_reg,
        x_9_hwPhi_V_read => x_9_hwPhi_V_read_int_reg,
        x_10_hwPhi_V_read => x_10_hwPhi_V_read_int_reg,
        x_11_hwPhi_V_read => x_11_hwPhi_V_read_int_reg,
        x_12_hwPhi_V_read => x_12_hwPhi_V_read_int_reg,
        x_13_hwPhi_V_read => x_13_hwPhi_V_read_int_reg,
        x_14_hwPhi_V_read => x_14_hwPhi_V_read_int_reg,
        x_15_hwPhi_V_read => x_15_hwPhi_V_read_int_reg,
        x_16_hwPhi_V_read => x_16_hwPhi_V_read_int_reg,
        x_17_hwPhi_V_read => x_17_hwPhi_V_read_int_reg,
        x_18_hwPhi_V_read => x_18_hwPhi_V_read_int_reg,
        x_19_hwPhi_V_read => x_19_hwPhi_V_read_int_reg,
        x_20_hwPhi_V_read => x_20_hwPhi_V_read_int_reg,
        x_21_hwPhi_V_read => x_21_hwPhi_V_read_int_reg,
        x_22_hwPhi_V_read => x_22_hwPhi_V_read_int_reg,
        x_23_hwPhi_V_read => x_23_hwPhi_V_read_int_reg,
        x_24_hwPhi_V_read => x_24_hwPhi_V_read_int_reg,
        x_25_hwPhi_V_read => x_25_hwPhi_V_read_int_reg,
        x_26_hwPhi_V_read => x_26_hwPhi_V_read_int_reg,
        x_27_hwPhi_V_read => x_27_hwPhi_V_read_int_reg,
        x_28_hwPhi_V_read => x_28_hwPhi_V_read_int_reg,
        x_29_hwPhi_V_read => x_29_hwPhi_V_read_int_reg,
        x_30_hwPhi_V_read => x_30_hwPhi_V_read_int_reg,
        x_31_hwPhi_V_read => x_31_hwPhi_V_read_int_reg,
        ap_return_0 => grp_reduce_3_fu_1554_ap_return_0,
        ap_return_1 => grp_reduce_3_fu_1554_ap_return_1,
        ap_return_2 => grp_reduce_3_fu_1554_ap_return_2,
        ap_ce => grp_reduce_3_fu_1554_ap_ce);

    grp_reduce_3_fu_1750 : component reduce_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_hwPt_V_read => x_32_hwPt_V_read_int_reg,
        x_1_hwPt_V_read => x_33_hwPt_V_read_int_reg,
        x_2_hwPt_V_read => x_34_hwPt_V_read_int_reg,
        x_3_hwPt_V_read => x_35_hwPt_V_read_int_reg,
        x_4_hwPt_V_read => x_36_hwPt_V_read_int_reg,
        x_5_hwPt_V_read => x_37_hwPt_V_read_int_reg,
        x_6_hwPt_V_read => x_38_hwPt_V_read_int_reg,
        x_7_hwPt_V_read => x_39_hwPt_V_read_int_reg,
        x_8_hwPt_V_read => x_40_hwPt_V_read_int_reg,
        x_9_hwPt_V_read => x_41_hwPt_V_read_int_reg,
        x_10_hwPt_V_read => x_42_hwPt_V_read_int_reg,
        x_11_hwPt_V_read => x_43_hwPt_V_read_int_reg,
        x_12_hwPt_V_read => x_44_hwPt_V_read_int_reg,
        x_13_hwPt_V_read => x_45_hwPt_V_read_int_reg,
        x_14_hwPt_V_read => x_46_hwPt_V_read_int_reg,
        x_15_hwPt_V_read => x_47_hwPt_V_read_int_reg,
        x_16_hwPt_V_read => x_48_hwPt_V_read_int_reg,
        x_17_hwPt_V_read => x_49_hwPt_V_read_int_reg,
        x_18_hwPt_V_read => x_50_hwPt_V_read_int_reg,
        x_19_hwPt_V_read => x_51_hwPt_V_read_int_reg,
        x_20_hwPt_V_read => x_52_hwPt_V_read_int_reg,
        x_21_hwPt_V_read => x_53_hwPt_V_read_int_reg,
        x_22_hwPt_V_read => x_54_hwPt_V_read_int_reg,
        x_23_hwPt_V_read => x_55_hwPt_V_read_int_reg,
        x_24_hwPt_V_read => x_56_hwPt_V_read_int_reg,
        x_25_hwPt_V_read => x_57_hwPt_V_read_int_reg,
        x_26_hwPt_V_read => x_58_hwPt_V_read_int_reg,
        x_27_hwPt_V_read => x_59_hwPt_V_read_int_reg,
        x_28_hwPt_V_read => x_60_hwPt_V_read_int_reg,
        x_29_hwPt_V_read => x_61_hwPt_V_read_int_reg,
        x_30_hwPt_V_read => x_62_hwPt_V_read_int_reg,
        x_31_hwPt_V_read => x_63_hwPt_V_read_int_reg,
        x_0_hwEta_V_read => x_32_hwEta_V_read_int_reg,
        x_1_hwEta_V_read => x_33_hwEta_V_read_int_reg,
        x_2_hwEta_V_read => x_34_hwEta_V_read_int_reg,
        x_3_hwEta_V_read => x_35_hwEta_V_read_int_reg,
        x_4_hwEta_V_read => x_36_hwEta_V_read_int_reg,
        x_5_hwEta_V_read => x_37_hwEta_V_read_int_reg,
        x_6_hwEta_V_read => x_38_hwEta_V_read_int_reg,
        x_7_hwEta_V_read => x_39_hwEta_V_read_int_reg,
        x_8_hwEta_V_read => x_40_hwEta_V_read_int_reg,
        x_9_hwEta_V_read => x_41_hwEta_V_read_int_reg,
        x_10_hwEta_V_read => x_42_hwEta_V_read_int_reg,
        x_11_hwEta_V_read => x_43_hwEta_V_read_int_reg,
        x_12_hwEta_V_read => x_44_hwEta_V_read_int_reg,
        x_13_hwEta_V_read => x_45_hwEta_V_read_int_reg,
        x_14_hwEta_V_read => x_46_hwEta_V_read_int_reg,
        x_15_hwEta_V_read => x_47_hwEta_V_read_int_reg,
        x_16_hwEta_V_read => x_48_hwEta_V_read_int_reg,
        x_17_hwEta_V_read => x_49_hwEta_V_read_int_reg,
        x_18_hwEta_V_read => x_50_hwEta_V_read_int_reg,
        x_19_hwEta_V_read => x_51_hwEta_V_read_int_reg,
        x_20_hwEta_V_read => x_52_hwEta_V_read_int_reg,
        x_21_hwEta_V_read => x_53_hwEta_V_read_int_reg,
        x_22_hwEta_V_read => x_54_hwEta_V_read_int_reg,
        x_23_hwEta_V_read => x_55_hwEta_V_read_int_reg,
        x_24_hwEta_V_read => x_56_hwEta_V_read_int_reg,
        x_25_hwEta_V_read => x_57_hwEta_V_read_int_reg,
        x_26_hwEta_V_read => x_58_hwEta_V_read_int_reg,
        x_27_hwEta_V_read => x_59_hwEta_V_read_int_reg,
        x_28_hwEta_V_read => x_60_hwEta_V_read_int_reg,
        x_29_hwEta_V_read => x_61_hwEta_V_read_int_reg,
        x_30_hwEta_V_read => x_62_hwEta_V_read_int_reg,
        x_31_hwEta_V_read => x_63_hwEta_V_read_int_reg,
        x_0_hwPhi_V_read => x_32_hwPhi_V_read_int_reg,
        x_1_hwPhi_V_read => x_33_hwPhi_V_read_int_reg,
        x_2_hwPhi_V_read => x_34_hwPhi_V_read_int_reg,
        x_3_hwPhi_V_read => x_35_hwPhi_V_read_int_reg,
        x_4_hwPhi_V_read => x_36_hwPhi_V_read_int_reg,
        x_5_hwPhi_V_read => x_37_hwPhi_V_read_int_reg,
        x_6_hwPhi_V_read => x_38_hwPhi_V_read_int_reg,
        x_7_hwPhi_V_read => x_39_hwPhi_V_read_int_reg,
        x_8_hwPhi_V_read => x_40_hwPhi_V_read_int_reg,
        x_9_hwPhi_V_read => x_41_hwPhi_V_read_int_reg,
        x_10_hwPhi_V_read => x_42_hwPhi_V_read_int_reg,
        x_11_hwPhi_V_read => x_43_hwPhi_V_read_int_reg,
        x_12_hwPhi_V_read => x_44_hwPhi_V_read_int_reg,
        x_13_hwPhi_V_read => x_45_hwPhi_V_read_int_reg,
        x_14_hwPhi_V_read => x_46_hwPhi_V_read_int_reg,
        x_15_hwPhi_V_read => x_47_hwPhi_V_read_int_reg,
        x_16_hwPhi_V_read => x_48_hwPhi_V_read_int_reg,
        x_17_hwPhi_V_read => x_49_hwPhi_V_read_int_reg,
        x_18_hwPhi_V_read => x_50_hwPhi_V_read_int_reg,
        x_19_hwPhi_V_read => x_51_hwPhi_V_read_int_reg,
        x_20_hwPhi_V_read => x_52_hwPhi_V_read_int_reg,
        x_21_hwPhi_V_read => x_53_hwPhi_V_read_int_reg,
        x_22_hwPhi_V_read => x_54_hwPhi_V_read_int_reg,
        x_23_hwPhi_V_read => x_55_hwPhi_V_read_int_reg,
        x_24_hwPhi_V_read => x_56_hwPhi_V_read_int_reg,
        x_25_hwPhi_V_read => x_57_hwPhi_V_read_int_reg,
        x_26_hwPhi_V_read => x_58_hwPhi_V_read_int_reg,
        x_27_hwPhi_V_read => x_59_hwPhi_V_read_int_reg,
        x_28_hwPhi_V_read => x_60_hwPhi_V_read_int_reg,
        x_29_hwPhi_V_read => x_61_hwPhi_V_read_int_reg,
        x_30_hwPhi_V_read => x_62_hwPhi_V_read_int_reg,
        x_31_hwPhi_V_read => x_63_hwPhi_V_read_int_reg,
        ap_return_0 => grp_reduce_3_fu_1750_ap_return_0,
        ap_return_1 => grp_reduce_3_fu_1750_ap_return_1,
        ap_return_2 => grp_reduce_3_fu_1750_ap_return_2,
        ap_ce => grp_reduce_3_fu_1750_ap_ce);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= select_ln84_fu_1982_p3;
                ap_return_1_int_reg <= select_ln84_3_fu_1990_p3;
                ap_return_2_int_reg <= select_ln84_4_fu_1998_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_0_hwEta_V_read_int_reg <= x_0_hwEta_V_read;
                x_0_hwPhi_V_read_int_reg <= x_0_hwPhi_V_read;
                x_0_hwPt_V_read_int_reg <= x_0_hwPt_V_read;
                x_10_hwEta_V_read_int_reg <= x_10_hwEta_V_read;
                x_10_hwPhi_V_read_int_reg <= x_10_hwPhi_V_read;
                x_10_hwPt_V_read_int_reg <= x_10_hwPt_V_read;
                x_11_hwEta_V_read_int_reg <= x_11_hwEta_V_read;
                x_11_hwPhi_V_read_int_reg <= x_11_hwPhi_V_read;
                x_11_hwPt_V_read_int_reg <= x_11_hwPt_V_read;
                x_12_hwEta_V_read_int_reg <= x_12_hwEta_V_read;
                x_12_hwPhi_V_read_int_reg <= x_12_hwPhi_V_read;
                x_12_hwPt_V_read_int_reg <= x_12_hwPt_V_read;
                x_13_hwEta_V_read_int_reg <= x_13_hwEta_V_read;
                x_13_hwPhi_V_read_int_reg <= x_13_hwPhi_V_read;
                x_13_hwPt_V_read_int_reg <= x_13_hwPt_V_read;
                x_14_hwEta_V_read_int_reg <= x_14_hwEta_V_read;
                x_14_hwPhi_V_read_int_reg <= x_14_hwPhi_V_read;
                x_14_hwPt_V_read_int_reg <= x_14_hwPt_V_read;
                x_15_hwEta_V_read_int_reg <= x_15_hwEta_V_read;
                x_15_hwPhi_V_read_int_reg <= x_15_hwPhi_V_read;
                x_15_hwPt_V_read_int_reg <= x_15_hwPt_V_read;
                x_16_hwEta_V_read_int_reg <= x_16_hwEta_V_read;
                x_16_hwPhi_V_read_int_reg <= x_16_hwPhi_V_read;
                x_16_hwPt_V_read_int_reg <= x_16_hwPt_V_read;
                x_17_hwEta_V_read_int_reg <= x_17_hwEta_V_read;
                x_17_hwPhi_V_read_int_reg <= x_17_hwPhi_V_read;
                x_17_hwPt_V_read_int_reg <= x_17_hwPt_V_read;
                x_18_hwEta_V_read_int_reg <= x_18_hwEta_V_read;
                x_18_hwPhi_V_read_int_reg <= x_18_hwPhi_V_read;
                x_18_hwPt_V_read_int_reg <= x_18_hwPt_V_read;
                x_19_hwEta_V_read_int_reg <= x_19_hwEta_V_read;
                x_19_hwPhi_V_read_int_reg <= x_19_hwPhi_V_read;
                x_19_hwPt_V_read_int_reg <= x_19_hwPt_V_read;
                x_1_hwEta_V_read_int_reg <= x_1_hwEta_V_read;
                x_1_hwPhi_V_read_int_reg <= x_1_hwPhi_V_read;
                x_1_hwPt_V_read_int_reg <= x_1_hwPt_V_read;
                x_20_hwEta_V_read_int_reg <= x_20_hwEta_V_read;
                x_20_hwPhi_V_read_int_reg <= x_20_hwPhi_V_read;
                x_20_hwPt_V_read_int_reg <= x_20_hwPt_V_read;
                x_21_hwEta_V_read_int_reg <= x_21_hwEta_V_read;
                x_21_hwPhi_V_read_int_reg <= x_21_hwPhi_V_read;
                x_21_hwPt_V_read_int_reg <= x_21_hwPt_V_read;
                x_22_hwEta_V_read_int_reg <= x_22_hwEta_V_read;
                x_22_hwPhi_V_read_int_reg <= x_22_hwPhi_V_read;
                x_22_hwPt_V_read_int_reg <= x_22_hwPt_V_read;
                x_23_hwEta_V_read_int_reg <= x_23_hwEta_V_read;
                x_23_hwPhi_V_read_int_reg <= x_23_hwPhi_V_read;
                x_23_hwPt_V_read_int_reg <= x_23_hwPt_V_read;
                x_24_hwEta_V_read_int_reg <= x_24_hwEta_V_read;
                x_24_hwPhi_V_read_int_reg <= x_24_hwPhi_V_read;
                x_24_hwPt_V_read_int_reg <= x_24_hwPt_V_read;
                x_25_hwEta_V_read_int_reg <= x_25_hwEta_V_read;
                x_25_hwPhi_V_read_int_reg <= x_25_hwPhi_V_read;
                x_25_hwPt_V_read_int_reg <= x_25_hwPt_V_read;
                x_26_hwEta_V_read_int_reg <= x_26_hwEta_V_read;
                x_26_hwPhi_V_read_int_reg <= x_26_hwPhi_V_read;
                x_26_hwPt_V_read_int_reg <= x_26_hwPt_V_read;
                x_27_hwEta_V_read_int_reg <= x_27_hwEta_V_read;
                x_27_hwPhi_V_read_int_reg <= x_27_hwPhi_V_read;
                x_27_hwPt_V_read_int_reg <= x_27_hwPt_V_read;
                x_28_hwEta_V_read_int_reg <= x_28_hwEta_V_read;
                x_28_hwPhi_V_read_int_reg <= x_28_hwPhi_V_read;
                x_28_hwPt_V_read_int_reg <= x_28_hwPt_V_read;
                x_29_hwEta_V_read_int_reg <= x_29_hwEta_V_read;
                x_29_hwPhi_V_read_int_reg <= x_29_hwPhi_V_read;
                x_29_hwPt_V_read_int_reg <= x_29_hwPt_V_read;
                x_2_hwEta_V_read_int_reg <= x_2_hwEta_V_read;
                x_2_hwPhi_V_read_int_reg <= x_2_hwPhi_V_read;
                x_2_hwPt_V_read_int_reg <= x_2_hwPt_V_read;
                x_30_hwEta_V_read_int_reg <= x_30_hwEta_V_read;
                x_30_hwPhi_V_read_int_reg <= x_30_hwPhi_V_read;
                x_30_hwPt_V_read_int_reg <= x_30_hwPt_V_read;
                x_31_hwEta_V_read_int_reg <= x_31_hwEta_V_read;
                x_31_hwPhi_V_read_int_reg <= x_31_hwPhi_V_read;
                x_31_hwPt_V_read_int_reg <= x_31_hwPt_V_read;
                x_32_hwEta_V_read_int_reg <= x_32_hwEta_V_read;
                x_32_hwPhi_V_read_int_reg <= x_32_hwPhi_V_read;
                x_32_hwPt_V_read_int_reg <= x_32_hwPt_V_read;
                x_33_hwEta_V_read_int_reg <= x_33_hwEta_V_read;
                x_33_hwPhi_V_read_int_reg <= x_33_hwPhi_V_read;
                x_33_hwPt_V_read_int_reg <= x_33_hwPt_V_read;
                x_34_hwEta_V_read_int_reg <= x_34_hwEta_V_read;
                x_34_hwPhi_V_read_int_reg <= x_34_hwPhi_V_read;
                x_34_hwPt_V_read_int_reg <= x_34_hwPt_V_read;
                x_35_hwEta_V_read_int_reg <= x_35_hwEta_V_read;
                x_35_hwPhi_V_read_int_reg <= x_35_hwPhi_V_read;
                x_35_hwPt_V_read_int_reg <= x_35_hwPt_V_read;
                x_36_hwEta_V_read_int_reg <= x_36_hwEta_V_read;
                x_36_hwPhi_V_read_int_reg <= x_36_hwPhi_V_read;
                x_36_hwPt_V_read_int_reg <= x_36_hwPt_V_read;
                x_37_hwEta_V_read_int_reg <= x_37_hwEta_V_read;
                x_37_hwPhi_V_read_int_reg <= x_37_hwPhi_V_read;
                x_37_hwPt_V_read_int_reg <= x_37_hwPt_V_read;
                x_38_hwEta_V_read_int_reg <= x_38_hwEta_V_read;
                x_38_hwPhi_V_read_int_reg <= x_38_hwPhi_V_read;
                x_38_hwPt_V_read_int_reg <= x_38_hwPt_V_read;
                x_39_hwEta_V_read_int_reg <= x_39_hwEta_V_read;
                x_39_hwPhi_V_read_int_reg <= x_39_hwPhi_V_read;
                x_39_hwPt_V_read_int_reg <= x_39_hwPt_V_read;
                x_3_hwEta_V_read_int_reg <= x_3_hwEta_V_read;
                x_3_hwPhi_V_read_int_reg <= x_3_hwPhi_V_read;
                x_3_hwPt_V_read_int_reg <= x_3_hwPt_V_read;
                x_40_hwEta_V_read_int_reg <= x_40_hwEta_V_read;
                x_40_hwPhi_V_read_int_reg <= x_40_hwPhi_V_read;
                x_40_hwPt_V_read_int_reg <= x_40_hwPt_V_read;
                x_41_hwEta_V_read_int_reg <= x_41_hwEta_V_read;
                x_41_hwPhi_V_read_int_reg <= x_41_hwPhi_V_read;
                x_41_hwPt_V_read_int_reg <= x_41_hwPt_V_read;
                x_42_hwEta_V_read_int_reg <= x_42_hwEta_V_read;
                x_42_hwPhi_V_read_int_reg <= x_42_hwPhi_V_read;
                x_42_hwPt_V_read_int_reg <= x_42_hwPt_V_read;
                x_43_hwEta_V_read_int_reg <= x_43_hwEta_V_read;
                x_43_hwPhi_V_read_int_reg <= x_43_hwPhi_V_read;
                x_43_hwPt_V_read_int_reg <= x_43_hwPt_V_read;
                x_44_hwEta_V_read_int_reg <= x_44_hwEta_V_read;
                x_44_hwPhi_V_read_int_reg <= x_44_hwPhi_V_read;
                x_44_hwPt_V_read_int_reg <= x_44_hwPt_V_read;
                x_45_hwEta_V_read_int_reg <= x_45_hwEta_V_read;
                x_45_hwPhi_V_read_int_reg <= x_45_hwPhi_V_read;
                x_45_hwPt_V_read_int_reg <= x_45_hwPt_V_read;
                x_46_hwEta_V_read_int_reg <= x_46_hwEta_V_read;
                x_46_hwPhi_V_read_int_reg <= x_46_hwPhi_V_read;
                x_46_hwPt_V_read_int_reg <= x_46_hwPt_V_read;
                x_47_hwEta_V_read_int_reg <= x_47_hwEta_V_read;
                x_47_hwPhi_V_read_int_reg <= x_47_hwPhi_V_read;
                x_47_hwPt_V_read_int_reg <= x_47_hwPt_V_read;
                x_48_hwEta_V_read_int_reg <= x_48_hwEta_V_read;
                x_48_hwPhi_V_read_int_reg <= x_48_hwPhi_V_read;
                x_48_hwPt_V_read_int_reg <= x_48_hwPt_V_read;
                x_49_hwEta_V_read_int_reg <= x_49_hwEta_V_read;
                x_49_hwPhi_V_read_int_reg <= x_49_hwPhi_V_read;
                x_49_hwPt_V_read_int_reg <= x_49_hwPt_V_read;
                x_4_hwEta_V_read_int_reg <= x_4_hwEta_V_read;
                x_4_hwPhi_V_read_int_reg <= x_4_hwPhi_V_read;
                x_4_hwPt_V_read_int_reg <= x_4_hwPt_V_read;
                x_50_hwEta_V_read_int_reg <= x_50_hwEta_V_read;
                x_50_hwPhi_V_read_int_reg <= x_50_hwPhi_V_read;
                x_50_hwPt_V_read_int_reg <= x_50_hwPt_V_read;
                x_51_hwEta_V_read_int_reg <= x_51_hwEta_V_read;
                x_51_hwPhi_V_read_int_reg <= x_51_hwPhi_V_read;
                x_51_hwPt_V_read_int_reg <= x_51_hwPt_V_read;
                x_52_hwEta_V_read_int_reg <= x_52_hwEta_V_read;
                x_52_hwPhi_V_read_int_reg <= x_52_hwPhi_V_read;
                x_52_hwPt_V_read_int_reg <= x_52_hwPt_V_read;
                x_53_hwEta_V_read_int_reg <= x_53_hwEta_V_read;
                x_53_hwPhi_V_read_int_reg <= x_53_hwPhi_V_read;
                x_53_hwPt_V_read_int_reg <= x_53_hwPt_V_read;
                x_54_hwEta_V_read_int_reg <= x_54_hwEta_V_read;
                x_54_hwPhi_V_read_int_reg <= x_54_hwPhi_V_read;
                x_54_hwPt_V_read_int_reg <= x_54_hwPt_V_read;
                x_55_hwEta_V_read_int_reg <= x_55_hwEta_V_read;
                x_55_hwPhi_V_read_int_reg <= x_55_hwPhi_V_read;
                x_55_hwPt_V_read_int_reg <= x_55_hwPt_V_read;
                x_56_hwEta_V_read_int_reg <= x_56_hwEta_V_read;
                x_56_hwPhi_V_read_int_reg <= x_56_hwPhi_V_read;
                x_56_hwPt_V_read_int_reg <= x_56_hwPt_V_read;
                x_57_hwEta_V_read_int_reg <= x_57_hwEta_V_read;
                x_57_hwPhi_V_read_int_reg <= x_57_hwPhi_V_read;
                x_57_hwPt_V_read_int_reg <= x_57_hwPt_V_read;
                x_58_hwEta_V_read_int_reg <= x_58_hwEta_V_read;
                x_58_hwPhi_V_read_int_reg <= x_58_hwPhi_V_read;
                x_58_hwPt_V_read_int_reg <= x_58_hwPt_V_read;
                x_59_hwEta_V_read_int_reg <= x_59_hwEta_V_read;
                x_59_hwPhi_V_read_int_reg <= x_59_hwPhi_V_read;
                x_59_hwPt_V_read_int_reg <= x_59_hwPt_V_read;
                x_5_hwEta_V_read_int_reg <= x_5_hwEta_V_read;
                x_5_hwPhi_V_read_int_reg <= x_5_hwPhi_V_read;
                x_5_hwPt_V_read_int_reg <= x_5_hwPt_V_read;
                x_60_hwEta_V_read_int_reg <= x_60_hwEta_V_read;
                x_60_hwPhi_V_read_int_reg <= x_60_hwPhi_V_read;
                x_60_hwPt_V_read_int_reg <= x_60_hwPt_V_read;
                x_61_hwEta_V_read_int_reg <= x_61_hwEta_V_read;
                x_61_hwPhi_V_read_int_reg <= x_61_hwPhi_V_read;
                x_61_hwPt_V_read_int_reg <= x_61_hwPt_V_read;
                x_62_hwEta_V_read_int_reg <= x_62_hwEta_V_read;
                x_62_hwPhi_V_read_int_reg <= x_62_hwPhi_V_read;
                x_62_hwPt_V_read_int_reg <= x_62_hwPt_V_read;
                x_63_hwEta_V_read_int_reg <= x_63_hwEta_V_read;
                x_63_hwPhi_V_read_int_reg <= x_63_hwPhi_V_read;
                x_63_hwPt_V_read_int_reg <= x_63_hwPt_V_read;
                x_6_hwEta_V_read_int_reg <= x_6_hwEta_V_read;
                x_6_hwPhi_V_read_int_reg <= x_6_hwPhi_V_read;
                x_6_hwPt_V_read_int_reg <= x_6_hwPt_V_read;
                x_7_hwEta_V_read_int_reg <= x_7_hwEta_V_read;
                x_7_hwPhi_V_read_int_reg <= x_7_hwPhi_V_read;
                x_7_hwPt_V_read_int_reg <= x_7_hwPt_V_read;
                x_8_hwEta_V_read_int_reg <= x_8_hwEta_V_read;
                x_8_hwPhi_V_read_int_reg <= x_8_hwPhi_V_read;
                x_8_hwPt_V_read_int_reg <= x_8_hwPt_V_read;
                x_9_hwEta_V_read_int_reg <= x_9_hwEta_V_read;
                x_9_hwPhi_V_read_int_reg <= x_9_hwPhi_V_read;
                x_9_hwPt_V_read_int_reg <= x_9_hwPt_V_read;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp199 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp200 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call193 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call197 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call193 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call197 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call193 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call197 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call193 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call197 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call193 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call197 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call193 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call197 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(select_ln84_fu_1982_p3, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= select_ln84_fu_1982_p3;
        end if; 
    end process;


    ap_return_1_assign_proc : process(select_ln84_3_fu_1990_p3, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= select_ln84_3_fu_1990_p3;
        end if; 
    end process;


    ap_return_2_assign_proc : process(select_ln84_4_fu_1998_p3, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= select_ln84_4_fu_1998_p3;
        end if; 
    end process;


    grp_reduce_3_fu_1554_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp199, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp199))) then 
            grp_reduce_3_fu_1554_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_3_fu_1554_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reduce_3_fu_1750_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp200, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp200))) then 
            grp_reduce_3_fu_1750_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_3_fu_1750_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1496_fu_1970_p2 <= "1" when (unsigned(grp_reduce_3_fu_1554_ap_return_0) < unsigned(grp_reduce_3_fu_1750_ap_return_0)) else "0";
    select_ln84_3_fu_1990_p3 <= 
        grp_reduce_3_fu_1554_ap_return_1 when (xor_ln1496_fu_1976_p2(0) = '1') else 
        grp_reduce_3_fu_1750_ap_return_1;
    select_ln84_4_fu_1998_p3 <= 
        grp_reduce_3_fu_1554_ap_return_2 when (xor_ln1496_fu_1976_p2(0) = '1') else 
        grp_reduce_3_fu_1750_ap_return_2;
    select_ln84_fu_1982_p3 <= 
        grp_reduce_3_fu_1554_ap_return_0 when (xor_ln1496_fu_1976_p2(0) = '1') else 
        grp_reduce_3_fu_1750_ap_return_0;
    xor_ln1496_fu_1976_p2 <= (icmp_ln1496_fu_1970_p2 xor ap_const_lv1_1);
end behav;
