-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_10_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_11_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_12_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_13_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_14_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_15_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_10_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_11_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_12_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_13_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_14_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_15_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_10_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_11_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_12_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_13_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_14_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    x_15_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of reduce_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal grp_reduce_fu_402_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_fu_402_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_fu_402_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal call_ret9_reg_576_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal call_ret9_reg_576_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal TemplateParticle_hwP_reg_582 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_fu_454_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_fu_454_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_fu_454_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal call_ret_reg_588_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal call_ret_reg_588_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal b_hwPt_V_read_assign_reg_594 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_fu_402_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call49 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call49 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call49 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp52 : BOOLEAN;
    signal grp_reduce_fu_454_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call53 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call53 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call53 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp53 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln1496_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1496_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln93_fu_536_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln93_3_fu_542_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln93_4_fu_550_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_0_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_2_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_3_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_4_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_5_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_6_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_7_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_8_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_9_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_10_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_11_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_12_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_13_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_14_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_15_hwPt_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal x_0_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_2_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_3_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_4_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_5_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_6_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_7_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_8_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_9_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_10_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_11_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_12_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_13_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_14_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_15_hwEta_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_0_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_2_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_3_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_4_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_5_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_6_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_7_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_8_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_9_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_10_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_11_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_12_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_13_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_14_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal x_15_hwPhi_V_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (9 downto 0);

    component reduce IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        x_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        x_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_reduce_fu_402 : component reduce
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_hwPt_V_read => x_0_hwPt_V_read_int_reg,
        x_1_hwPt_V_read => x_1_hwPt_V_read_int_reg,
        x_2_hwPt_V_read => x_2_hwPt_V_read_int_reg,
        x_3_hwPt_V_read => x_3_hwPt_V_read_int_reg,
        x_4_hwPt_V_read => x_4_hwPt_V_read_int_reg,
        x_5_hwPt_V_read => x_5_hwPt_V_read_int_reg,
        x_6_hwPt_V_read => x_6_hwPt_V_read_int_reg,
        x_7_hwPt_V_read => x_7_hwPt_V_read_int_reg,
        x_0_hwEta_V_read => x_0_hwEta_V_read_int_reg,
        x_1_hwEta_V_read => x_1_hwEta_V_read_int_reg,
        x_2_hwEta_V_read => x_2_hwEta_V_read_int_reg,
        x_3_hwEta_V_read => x_3_hwEta_V_read_int_reg,
        x_4_hwEta_V_read => x_4_hwEta_V_read_int_reg,
        x_5_hwEta_V_read => x_5_hwEta_V_read_int_reg,
        x_6_hwEta_V_read => x_6_hwEta_V_read_int_reg,
        x_7_hwEta_V_read => x_7_hwEta_V_read_int_reg,
        x_0_hwPhi_V_read => x_0_hwPhi_V_read_int_reg,
        x_1_hwPhi_V_read => x_1_hwPhi_V_read_int_reg,
        x_2_hwPhi_V_read => x_2_hwPhi_V_read_int_reg,
        x_3_hwPhi_V_read => x_3_hwPhi_V_read_int_reg,
        x_4_hwPhi_V_read => x_4_hwPhi_V_read_int_reg,
        x_5_hwPhi_V_read => x_5_hwPhi_V_read_int_reg,
        x_6_hwPhi_V_read => x_6_hwPhi_V_read_int_reg,
        x_7_hwPhi_V_read => x_7_hwPhi_V_read_int_reg,
        ap_return_0 => grp_reduce_fu_402_ap_return_0,
        ap_return_1 => grp_reduce_fu_402_ap_return_1,
        ap_return_2 => grp_reduce_fu_402_ap_return_2,
        ap_ce => grp_reduce_fu_402_ap_ce);

    grp_reduce_fu_454 : component reduce
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_hwPt_V_read => x_8_hwPt_V_read_int_reg,
        x_1_hwPt_V_read => x_9_hwPt_V_read_int_reg,
        x_2_hwPt_V_read => x_10_hwPt_V_read_int_reg,
        x_3_hwPt_V_read => x_11_hwPt_V_read_int_reg,
        x_4_hwPt_V_read => x_12_hwPt_V_read_int_reg,
        x_5_hwPt_V_read => x_13_hwPt_V_read_int_reg,
        x_6_hwPt_V_read => x_14_hwPt_V_read_int_reg,
        x_7_hwPt_V_read => x_15_hwPt_V_read_int_reg,
        x_0_hwEta_V_read => x_8_hwEta_V_read_int_reg,
        x_1_hwEta_V_read => x_9_hwEta_V_read_int_reg,
        x_2_hwEta_V_read => x_10_hwEta_V_read_int_reg,
        x_3_hwEta_V_read => x_11_hwEta_V_read_int_reg,
        x_4_hwEta_V_read => x_12_hwEta_V_read_int_reg,
        x_5_hwEta_V_read => x_13_hwEta_V_read_int_reg,
        x_6_hwEta_V_read => x_14_hwEta_V_read_int_reg,
        x_7_hwEta_V_read => x_15_hwEta_V_read_int_reg,
        x_0_hwPhi_V_read => x_8_hwPhi_V_read_int_reg,
        x_1_hwPhi_V_read => x_9_hwPhi_V_read_int_reg,
        x_2_hwPhi_V_read => x_10_hwPhi_V_read_int_reg,
        x_3_hwPhi_V_read => x_11_hwPhi_V_read_int_reg,
        x_4_hwPhi_V_read => x_12_hwPhi_V_read_int_reg,
        x_5_hwPhi_V_read => x_13_hwPhi_V_read_int_reg,
        x_6_hwPhi_V_read => x_14_hwPhi_V_read_int_reg,
        x_7_hwPhi_V_read => x_15_hwPhi_V_read_int_reg,
        ap_return_0 => grp_reduce_fu_454_ap_return_0,
        ap_return_1 => grp_reduce_fu_454_ap_return_1,
        ap_return_2 => grp_reduce_fu_454_ap_return_2,
        ap_ce => grp_reduce_fu_454_ap_ce);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                TemplateParticle_hwP_reg_582 <= grp_reduce_fu_402_ap_return_0;
                b_hwPt_V_read_assign_reg_594 <= grp_reduce_fu_454_ap_return_0;
                call_ret9_reg_576_1 <= grp_reduce_fu_402_ap_return_1;
                call_ret9_reg_576_2 <= grp_reduce_fu_402_ap_return_2;
                call_ret_reg_588_1 <= grp_reduce_fu_454_ap_return_1;
                call_ret_reg_588_2 <= grp_reduce_fu_454_ap_return_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= select_ln93_fu_536_p3;
                ap_return_1_int_reg <= select_ln93_3_fu_542_p3;
                ap_return_2_int_reg <= select_ln93_4_fu_550_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_0_hwEta_V_read_int_reg <= x_0_hwEta_V_read;
                x_0_hwPhi_V_read_int_reg <= x_0_hwPhi_V_read;
                x_0_hwPt_V_read_int_reg <= x_0_hwPt_V_read;
                x_10_hwEta_V_read_int_reg <= x_10_hwEta_V_read;
                x_10_hwPhi_V_read_int_reg <= x_10_hwPhi_V_read;
                x_10_hwPt_V_read_int_reg <= x_10_hwPt_V_read;
                x_11_hwEta_V_read_int_reg <= x_11_hwEta_V_read;
                x_11_hwPhi_V_read_int_reg <= x_11_hwPhi_V_read;
                x_11_hwPt_V_read_int_reg <= x_11_hwPt_V_read;
                x_12_hwEta_V_read_int_reg <= x_12_hwEta_V_read;
                x_12_hwPhi_V_read_int_reg <= x_12_hwPhi_V_read;
                x_12_hwPt_V_read_int_reg <= x_12_hwPt_V_read;
                x_13_hwEta_V_read_int_reg <= x_13_hwEta_V_read;
                x_13_hwPhi_V_read_int_reg <= x_13_hwPhi_V_read;
                x_13_hwPt_V_read_int_reg <= x_13_hwPt_V_read;
                x_14_hwEta_V_read_int_reg <= x_14_hwEta_V_read;
                x_14_hwPhi_V_read_int_reg <= x_14_hwPhi_V_read;
                x_14_hwPt_V_read_int_reg <= x_14_hwPt_V_read;
                x_15_hwEta_V_read_int_reg <= x_15_hwEta_V_read;
                x_15_hwPhi_V_read_int_reg <= x_15_hwPhi_V_read;
                x_15_hwPt_V_read_int_reg <= x_15_hwPt_V_read;
                x_1_hwEta_V_read_int_reg <= x_1_hwEta_V_read;
                x_1_hwPhi_V_read_int_reg <= x_1_hwPhi_V_read;
                x_1_hwPt_V_read_int_reg <= x_1_hwPt_V_read;
                x_2_hwEta_V_read_int_reg <= x_2_hwEta_V_read;
                x_2_hwPhi_V_read_int_reg <= x_2_hwPhi_V_read;
                x_2_hwPt_V_read_int_reg <= x_2_hwPt_V_read;
                x_3_hwEta_V_read_int_reg <= x_3_hwEta_V_read;
                x_3_hwPhi_V_read_int_reg <= x_3_hwPhi_V_read;
                x_3_hwPt_V_read_int_reg <= x_3_hwPt_V_read;
                x_4_hwEta_V_read_int_reg <= x_4_hwEta_V_read;
                x_4_hwPhi_V_read_int_reg <= x_4_hwPhi_V_read;
                x_4_hwPt_V_read_int_reg <= x_4_hwPt_V_read;
                x_5_hwEta_V_read_int_reg <= x_5_hwEta_V_read;
                x_5_hwPhi_V_read_int_reg <= x_5_hwPhi_V_read;
                x_5_hwPt_V_read_int_reg <= x_5_hwPt_V_read;
                x_6_hwEta_V_read_int_reg <= x_6_hwEta_V_read;
                x_6_hwPhi_V_read_int_reg <= x_6_hwPhi_V_read;
                x_6_hwPt_V_read_int_reg <= x_6_hwPt_V_read;
                x_7_hwEta_V_read_int_reg <= x_7_hwEta_V_read;
                x_7_hwPhi_V_read_int_reg <= x_7_hwPhi_V_read;
                x_7_hwPt_V_read_int_reg <= x_7_hwPt_V_read;
                x_8_hwEta_V_read_int_reg <= x_8_hwEta_V_read;
                x_8_hwPhi_V_read_int_reg <= x_8_hwPhi_V_read;
                x_8_hwPt_V_read_int_reg <= x_8_hwPt_V_read;
                x_9_hwEta_V_read_int_reg <= x_9_hwEta_V_read;
                x_9_hwPhi_V_read_int_reg <= x_9_hwPhi_V_read;
                x_9_hwPt_V_read_int_reg <= x_9_hwPt_V_read;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp52 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp53 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call49 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call53 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call49 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call53 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call49 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call53 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(select_ln93_fu_536_p3, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= select_ln93_fu_536_p3;
        end if; 
    end process;


    ap_return_1_assign_proc : process(select_ln93_3_fu_542_p3, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= select_ln93_3_fu_542_p3;
        end if; 
    end process;


    ap_return_2_assign_proc : process(select_ln93_4_fu_550_p3, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= select_ln93_4_fu_550_p3;
        end if; 
    end process;


    grp_reduce_fu_402_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp52, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp52))) then 
            grp_reduce_fu_402_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_fu_402_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reduce_fu_454_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp53, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp53))) then 
            grp_reduce_fu_454_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_fu_454_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1496_fu_526_p2 <= "1" when (unsigned(TemplateParticle_hwP_reg_582) < unsigned(b_hwPt_V_read_assign_reg_594)) else "0";
    select_ln93_3_fu_542_p3 <= 
        call_ret9_reg_576_1 when (xor_ln1496_fu_530_p2(0) = '1') else 
        call_ret_reg_588_1;
    select_ln93_4_fu_550_p3 <= 
        call_ret9_reg_576_2 when (xor_ln1496_fu_530_p2(0) = '1') else 
        call_ret_reg_588_2;
    select_ln93_fu_536_p3 <= 
        TemplateParticle_hwP_reg_582 when (xor_ln1496_fu_530_p2(0) = '1') else 
        b_hwPt_V_read_assign_reg_594;
    xor_ln1496_fu_530_p2 <= (icmp_ln1496_fu_526_p2 xor ap_const_lv1_1);
end behav;
